apiVersion: v1
kind: ReplicationController
metadata:
  name: go-docker-rc
spec:
  replicas: 3
  selector:
    app: go-docker
  template:
    metadata:
      labels:
        app: go-docker
    spec:
      containers:
        - name: go-docker
          image: vchilikov/go-docker
          ports:
          - containerPort: 9000